/* 26 EXERCICIOS */

/* 1 EX */
UPDATE debitos SET SITUACAO_DEBITO = 'Atrasado'
WHERE DATAVENCIMENTO < CURRENT_DATE
AND SITUACAO_DEBITO NOT IN ('Negociado', 'Pago');

SELECT * FROM DEBITOS d 

/* 2 EX */
UPDATE debitos SET SITUACAO_DEBITO = 'Pendente'
WHERE DATAVENCIMENTO >= CURRENT_DATE
AND SITUACAO_DEBITO != 'Pago';

SELECT * FROM DEBITOS d 

/* 3 EX */


/* 4 EX */
SELECT NOME, EMAIL, TELEFONE
FROM PESSOA p ;

/* 5 EX */
SELECT NOME, DESCRICAO, PRECO_UNITARIO
FROM PRODUTO p 
WHERE PRECO_UNITARIO > 100;

/* 6 EX */
SELECT DATA_VENDA, VALOR_TOTAL, ID_FUNCIONARIO, ID_FORMA_PAGAMENTO
FROM VENDA v 
WHERE DATA_VENDA = '2023-09-20';  

/* 7 EX */


/* 8 EX */
SELECT p.NOME, p.EMAIL, p.TELEFONE, d.DATAVENCIMENTO, d.SITUACAO_DEBITO
FROM cliente c
INNER JOIN pessoa p ON c.ID_PESSOA = p.ID_PESSOA
LEFT JOIN DEBITOS d ON c.ID_CLIENTE = d.ID_CLIENTE
ORDER BY p.NOME;

/* 10 EX */


/* 11 EX */
UPDATE produto SET PRECO_UNITARIO = PRECO_UNITARIO * 1.10
WHERE QUANTIDADE_ESTOQUE < 10;

/* 13 EX */
UPDATE DEBITOS d SET d.SITUACAO_DEBITO = 'Pagos'
WHERE d.SITUACAO_DEBITO = 'Atrasado'
  AND EXISTS (
    SELECT 1
    FROM pagamento p
    WHERE p.ID_DEBITO = d.ID_DEBITO
  );

/* 15 EX */
SELECT *
FROM VENDA
WHERE DATA_VENDA BETWEEN '2023-12-01' AND '2024-01-31';

/* 16 EX */
SELECT *
FROM PRODUTO
WHERE QUANTIDADE_ESTOQUE BETWEEN 5 AND 20;

/* 17 EX */
SELECT *
FROM PESSOA
WHERE NOME LIKE 'A%';

/* 18 EX */


/* 19 EX */


/* 20 EX */


/* 21 EX */


/* 22 EX */


/* 23 EX */


/* 24 EX */


/* 25 EX */








